server:
  port: 8084
spring:
  application:
    name: message-service
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true

# JWT Configuration
jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24 hours in milliseconds

# Security Configuration
logging:
  level:
    co.edu.uptc: DEBUG
    org.springframework.security: DEBUG